### ISSUE TITLE
Clarify use of `ReactPropsFromRemoteComponentType` in comprehensive example

### ISSUE THREAD

**Issue by joeyfreund** [Shopify/remote-ui#124]
The [comprehensive example](https://github.com/Shopify/remote-ui/blob/main/documentation/comprehensive-example.md) contains a code snippet that import `ReactPropsFromRemoteComponentType` and mentions it in an inline comment, but doesn't actually use it in the code.

![image](https://user-images.githubusercontent.com/6747775/135650719-2beb66cf-adbf-4a5a-b03d-b61150193b4d.png)

**Comment by lemonmade** [comment]
The comprehensive example was reworked as part of [refactoring remote-ui onto the DOM](https://github.com/Shopify/remote-ui/discussions/267).
