### ISSUE TITLE
Update the vanilla DOM example to a counter app

### ISSUE THREAD

**Issue by joeyfreund** [Shopify/remote-ui#131]
The [vanilla DOM example](https://github.com/Shopify/remote-ui/tree/main/examples/vanilla-dom) provides users with a basic-yet-complete example of remote ui.

We can improve the example by making it a bit more visual.

### Current state

Remote `Button` component calls `api.getMessage` on click, and logs the message to the console.

### Desired state

Instead of logging to the console, let's make the example more visual and have something changing on the screen when the button is clicked.

My suggestion is to go with the classic example ... a  counter app:

 - Instead of the text input, the host will show the count in a non-input element (e.g. `p`, `span`, `div`)
 - Instead of `api.getMessage`, the host will provide `api.getCount` and `api.setCount`
 - The `Button` is still remote, the only different is the onPress logic (increment and set the count, instead of console.log)

For more context, see [this comment](https://github.com/Shopify/remote-ui/pull/127#pullrequestreview-782065668).

**Comment by nguyenhung15913** [comment]
Hi @joeyfreund. I am a student and joining an open source course. I would like to contribute to open source community. May I ask a question? I went to the <code>remote.js</code> and saw this line <code>const message = await api.getMessage()</code>. Could you please explain to me that where dose the getMessage() come from?

**Comment by joeyfreund** [comment]
Hi @nguyenhung15913 , that's awesome that you're interested in contributing to `remote-ui`!

The `api` object (that includes a `getMessage`) object is [passed from the host](https://github.com/Shopify/remote-ui/blob/main/examples/vanilla-dom/app/host.js#L46-48).

If you look at what the `getMessage` function does, you'll see that it returns the text that the user has entered in the text field. The important thing to note is that the text field is managed by the host, and the remote does NOT have direct access to the text field. The remote can only access what the host makes available to it (via the `api` object).

Does this clarify the situation?

**Comment by leocxy** [comment]
Hello @joeyfreund , I am playing around with the example, but the remote iframe does not append the button to the parent window. Do you know what is going on?

I am using node v16.18.0, OS is macOS Monterey 12.6.

**Comment by joeyfreund** [comment]
@leocxy , thanks for tagging me.

@lemonmade , when I run the vanilla DOM example, most of the time, the `render` method on the remote isn't called and the button is NOT renders:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/6747775/215355744-bb5e4ce0-26f1-4343-85ed-67eaa6ad2b27.png">

Every now and then (fairly rarely), the button renders and everything works fine.


Before I dig into this, any idea what might cause this issue?

**Comment by robin-drexler** [comment]
@joeyfreund I think this caused by a race condition in the iframe communication. A hotfix can be seen here: https://github.com/Shopify/remote-ui/pull/207 

But I do agree with @lemonmade's comment on that PR that we should fix the underlying problem (instead)

**Comment by lemonmade** [comment]
I wrote new example as part of [refactoring remote-ui onto the DOM](https://github.com/Shopify/remote-ui/discussions/267).
