### ISSUE TITLE
Error in iframe-parent: null is not an object (evaluating 'e.contentWindow.postMessage')

### ISSUE THREAD

**Issue by kumar303** [Shopify/remote-ui#184]
In Shopify's production bug tracker, we're seeing a high frequency of an error at [this line](https://github.com/Shopify/remote-ui/blob/66b10f13a04077681888789f6215ae75350c3a6e/packages/rpc/src/adaptors/iframe-parent.ts#L34):

```
TypeError null is not an object (evaluating 'e.contentWindow.postMessage') 
    node_modules/@remote-ui/rpc/build/esnext/adaptors/iframe-parent.esnext:28:27 
    [native code] asyncFunctionResume
    [native code] 
    [native code] promiseReactionJobWithoutPromise
```

It happens in these browsers: Mobile Safari, Mobile Safari UI/WKWebView, Chrome Mobile iOS, Safari.

I'm not sure if it's a compat issue or a cross domain issue.

**Comment by kumar303** [comment]
I don't think we updated `remote-ui` recently. @jamesvidler do you know?

**Comment by marvinhagemeister** [comment]
Just checked: The last time we updated `remote-ui` was about 3 weeks ago, way before #183 .

**Comment by kumar303** [comment]
Thanks for these detailed notes 👍 

> Semi-related to this, the `iframeReadyPromise` has a bug where it will continuously listen to `message` events even after the promise is resolved/the iframe is removed. This causes a memory leak.

I see it [here](https://github.com/Shopify/remote-ui/blob/89f838840f7bd54f2e09cbe31276e84d634db1f0/packages/rpc/src/adaptors/iframe-parent.ts#L21), too. Good catch. Can you file a separate issue for that?

**Comment by TheCloudlessSky** [comment]
@kumar303 done in #192!
