### ISSUE TITLE
Testing subscribable state changes

### ISSUE THREAD

**Issue by jduff** [Shopify/remote-ui#188]
I'm using the testing helpers described [here](https://github.com/Shopify/remote-ui/tree/main/packages/testing#usage) to create an extension tree and test the behaviour. I'm using the following function to build a stateful subscriber to mimic things like `lines` or `appMetafields` from the [extensions API](https://github.com/Shopify/ui-extensions/blob/4f65d05243fc387e949950741984f1b8604cad49/packages/checkout-ui-extensions/src/extension-points/api/standard/index.ts#L578).

```
function createRemoteSubscribable<T>(initial: T, result: T) {
  const subscription = {
    initial: initial,
    subscribe: (subscriber: Subscriber<T>):RemoteSubscribeResult<T> => {
      return [() => {}, result]
    }
  }

  return makeStatefulSubscribable<T>(subscription)
}
```

I'm using it like this:
```
    const extensionApi = {
      lines: createRemoteSubscribable<CartLine[]>([], [
        new CartLine(...),
      ]),
      appMetafields: createRemoteSubscribable<AppMetafieldEntry[]>([], [
        new Metafields(...),
      ])
    }

    const app = await mount(async (root) => {
      // This is where we are simulating Shopify calling the extension point.
      renderExtension(root, extensionApi)
    });
```

Within `renderExtension`:
```
appMetafields.subscribe(() => { // handle the metafields changing })
lines.subscribe(() => { // handle the cart lines changing })
```

All of this works for an initial render, but I would like to test `lines` or `appMetafields` changing and triggering the callback again and I can't figure out how to do that.

**Comment by lemonmade** [comment]
Hey John! We don't have anything built-in to help you with this, but you could adjust a few things in your current test utilities to make this work for you. I'd recommend making an object that lets you control the subscription’s value from the test:

```ts
function createControlledSubscribable<T>(initial: T) {
  let current: initial;
  const subscribers = new Set<Subscriber<T>>();

  return {
    get initial() {
      return current;
    },
    set(value: T) {
      current = value;
      for (const subscriber of subscribers) {
        subscriber(current);
      }
    },
    subscribe: (subscriber: Subscriber<T>): RemoteSubscribeResult<T> => {
      subscribers.add(subscriber);
      return [() => subscribers.delete(subscriber), current];
    }
  }
}
```

In your tests, you could then create these, use them as the source of the "remote subscribables" you are mocking for your extension, and then perform updates to them as part of the test setup:

```ts
const lines = createControlledSubscribable([new CartLine()]);
const metafields = createControlledSubscribable([new Metafields()]);

const api = {lines: makeStatefulSubscribable(lines), metafields: makeStatefulSubscribable(metafields)};

const app = await mount(async (root) => {
  renderExtension(root, api);
});

await app.act(() => {
  metafields.set([new Metafields(), new Metafields()]);
});

// Do your assertion
```

**Comment by jduff** [comment]
Thanks Chris! This controlled subscribable object looks like exactly what I was looking for.

I'll give this a try and let you know how it works out.

**Comment by jduff** [comment]
Just wanted to circle back to let you know this worked perfectly, thanks again!
