### ISSUE TITLE
append or appendChild?

### ISSUE THREAD

**Issue by L3P3** [Shopify/remote-ui#228]
In the [readme](https://github.com/Shopify/remote-ui/tree/main/packages/core#remoterootappend), it says `append` but in the [example code](https://www.npmjs.com/package/@shopify/checkout-ui-extensions) it says `appendChild`. Which one is correct or what do I miss?

**Comment by lemonmade** [comment]
Hi @L3P3. The library supports both `append` and `appendChild`, so you are free to choose whichever you prefer. The example you linked to is just one library that uses remote-ui under the hood, and was never updated to use the more recently-added `append` method.
