### ISSUE TITLE
Error objects lost during serialization

### ISSUE THREAD

**Issue by emileber** [Shopify/remote-ui#234]
## Context

When using `@remote-ui/rpc` or any package using it, built-in error objects are serialized as `{}`, which is unhelpful as any relevant information about errors happening in any function on the other side (iframe, web worker, etc) is lost when it reaches the host.

## Hypothesis

Since built-in error object keys aren't enumerable, when an error instance gets serialized, it detects no keys and gets serialized as `{}`. 

When looking at the [@remote-ui/rpc package's code](https://github.com/Shopify/remote-ui/blob/2e087c0955811a7675a063e5ea15a1146662f9d2/packages/rpc/src/encoding/basic.ts#L98), it seems to confirm my assumption:

```ts
      if (isBasicObject(value)) {
        seen.set(value, [undefined]);

        const transferables: Transferable[] = [];
        const result = Object.keys(value).reduce((object, key) => {
```

## Possible solutions

According to MDN's page on Error:

> Error is a [serializable object](https://developer.mozilla.org/en-US/docs/Glossary/Serializable_object), so it can be cloned with [`structuredClone()`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) or copied between [Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) using [`postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage).

What if we included a new case where we could treat `instanceof Error` as if it was a primitive to be transferred as-is?

Or would it make sense to switch to [`Object.getOwnPropertyNames()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) instead of `Object.keys` to get non-enumerable string properties as well?

```js
Object.keys(error)
// => []
Object.getOwnPropertyNames(error)
// => ['stack', 'message']
```

**Comment by emileber** [comment]
For visibility and feedback: @lemonmade @robin-drexler @kencwng

**Comment by lemonmade** [comment]
I'd be in favor of special-casing `Error` instances, although it does seem odd to return an error instead of throwing it (which is already handled, for functions proxied via `@remote-ui/rpc`).
