### ISSUE TITLE
SignalRemoteReceiver doesn't work if `@preact/signals` isn't imported in host

### ISSUE THREAD

**Issue by robin-drexler** [Shopify/remote-ui#507]
If you don't import `@preact/signals` in the host app, `SignalRemoteReceiver` children never update and hence never render anything if you use the `RemoteRootRenderer`

**Comment by lemonmade** [comment]
Added a note about the need to import `@preact/signals` to the README: https://github.com/Shopify/remote-dom/commit/7166dda0a7741023d6aece83232a7f6e91e98708
