### ISSUE TITLE
Support fragment as a child

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/remote-ui#89]
## What?

Fragment (aka sub tree as prop) is supported since this PR https://github.com/Shopify/checkout-web/pull/4809. Currently, fragment is only available as a prop. It would be ideal to have fragment as a child too.

**Comment by lemonmade** [comment]
The `RemoteFragment` concept is being removed as part of [refactoring remote-ui onto the DOM](https://github.com/Shopify/remote-ui/discussions/267).
