### ISSUE TITLE
RFC: removing the web-worker package and simplifying the repo

### ISSUE THREAD

**Issue by lemonmade** [Shopify/remote-ui#96]
This repo contains a bunch of different packages. In my mind, I kind of group them like this:

1. The "core" packages — `@remote-ui/core` and `@remote-ui/rpc` — which work together to do the minimum thing that remote-ui promises to do.
2. The "integration" packages — `@remote-ui/{react,vue,dom,htm,mini-react}` — which implement one or both of a host and remote integration for remote-ui.
3. The "utility" packages — `@remote-ui/async-subscriptions` and `@remote-ui/testing` — which offer developers common utilities they would need when using remote-ui for the kinds of problems we expect it to solve.

I think all of these packages are useful and appropriate to have in a repo together. There is one that doesn't fit in these categories to me, though: `@remote-ui/web-workers`. This library is probably the most "complex" one of the bunch, and much of the comprehensive example goes towards explaining its use. It's also very limited in its usefulness — it really only supports Webpack 4/5. Even though it does a very useful thing — a nice abstraction for strongly-typed workers — it's not strictly necessary for using remote-ui. There are many alternative ways of constructing web workers, all of which work just fine with the rest of remote-ui, and if you aren't using webpack, you have no choice but to ignore `@remote-ui/web-workers` anyways.

The web-worker library is also a bit weird in that it existed before the rest of remote-ui. We actually built it into quilt initially, and a version of it still exists there: https://github.com/Shopify/quilt/tree/main/packages/web-worker. Reflecting back on it, I think this was the right place for the code to live — it is a very specific implementation of web-workers that is mostly tied into Shopify's way of doing build tooling, and is not really a general-purpose library that fits in with the rest of remote-ui, which is completely oblivious to Shopify's tooling choices.

So here's my proposal:

1. We update `@shopify/web-worker` to be based on `@remote-ui/rpc` (it is currently tied to a separate `@shopify/rpc`, but that library was basically copied over to remote-ui, and using the remote-ui version seems fine to me. Shopify's admin and checkout can go back to depending on that library, instead of remote-ui's version.
1. We remove `@remote-ui/web-workers` from this repo and deprecate the package.
1. We rewrite the comprehensive example to not require any build tooling at all, and instead show a "web-native" example that uses native ESM (this isn't widely supported in workers, but is in Chrome, and simplifies the example down considerably).
1. We remove the create-react-app example, and replace it with two more modern alternatives: a web-native version that basically corresponds to what the comprehensive example showed, and a Vite-powered example (Vite is very fast, has almost no dependencies, and natively supports basic worker creation.

cc/ @henrytao-me @vividviolet

**Comment by vividviolet** [comment]
@lemonmade this makes sense to me. When we deprecate should we still have a README that links to @shopify/web-worker` and `@shopify/react-web-worker` in case anyone is looking for it?

**Comment by lemonmade** [comment]
@vividviolet yeah for sure, I'll add a deprecation notice to the package and point to those packages 👍

**Comment by dahukish** [comment]
As a note these are the currently consuming repos:
Shopify/remote-ui
Shopify/checkout-web
Shopify/web
Shopify/argo-admin-cli
Shopify/self-serve-web-prototype
Shopify/customer-account-prototype
Shopify/shopify-mobile
Shopify/remote-ui-private
Shopify/services-db
Shopify/argo-admin
Shopify/web-ui-extensions
Shopify/email

**Comment by lemonmade** [comment]
@BPScott I believe the both `@remote-ui/rpc` and `@remote-ui/web-workers` are backwards compatible with their `@shopify` equivalent — in an unusual show of restraint, we still have both of those on 1.x versions and have only added a few minor features to both as far as I can remember (I will verify for sure before pressing any buttons, obviously :D)

Yes, after this change, I will deprecate `@shopify/rpc`. Do we have a convention on whether the code for those packages stays in the repo, or is removed?

**Comment by BPScott** [comment]
> Do we have a convention on whether the code for those packages stays in the repo, or is removed?

Current qulity convention is to [delete code but leave a README in the package's folder](https://github.com/Shopify/quilt/tree/main/packages/react-effect-apollo) but honestly I don't like that and think it is pointlessly confusing.

In SKN I've done the following for deprecations:

- Delete code, leaving just a readme stating that the package has been obsolteded, changelog and package.json
- Publish a new major version of the package - which just contains a README saying there's nothing here
- Delete the whole package folder from the monorepo.

**Comment by glocore** [comment]
> We remove the create-react-app example, and replace it with two more modern alternatives: a web-native version that basically corresponds to what the comprehensive example showed, and a Vite-powered example (Vite is very fast, has almost no dependencies, and natively supports basic worker creation.

Would love to see a Vite-powered example! I tried using their official `react`/`react-ts` boilerplates, but I see the following error when using JSX in a worker script:
```
Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
```

I appreciate that this isn't exactly an issue with remote-ui. I'm just curious if anyone's had any luck getting it to work with Vite.

Minimal reproduction: https://github.com/glocore/vite-remote-ui-example

**Comment by glocore** [comment]
Update: [I got it working with Vite!](https://github.com/glocore/vite-remote-ui-example)
I had to disable React fast refresh in Vite config.
I'll be happy to create a PR to add it alongside the vanilla-dom example!
