### ISSUE TITLE
Remove DOM reference in remote-ui like MessagePort

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/remote-ui#98]
React Native is initially built without WebWorker but different Javascript Sandbox and reuses same worker.ts. However, `MessagePort` is not available in that sandbox. So, RN has to mock it. I think it's better to not refer to DOM at all in remote-ui library. `MessagePort` is the only thing I know in the repo.

**Comment by lemonmade** [comment]
As part of [refactoring remote-ui onto the DOM](https://github.com/Shopify/remote-ui/discussions/267), I removed references to `MessagePort`.
